Landing
rez0nat0r/react-learning pull request #1
Opened 2022-08-29 15:34 UTC by rez0nat0r

Landing. Created rep, branch, and started files for project ART.

2022-08-30 11:06 UTC, vickierose requested changes

2022-08-30 11:06 UTC, vickierose commented on src/app.js
> +    <>
in this case you don't need to wrap Home into empty tag

2022-08-30 11:06 UTC, vickierose commented on src/componentsBasic/home/home-sections/home-Info/home-info.scss
> +      padding-right: 11%;
I wouldn't recommend to write paddings in %. Could you please explain why is that so or change it to px value

2022-08-30 11:06 UTC, vickierose commented on src/componentsBasic/home/home-sections/home-Info/home-info.js
> +import "./home-info.scss";
files with components should be named with PascalCase, e.g App.js SomeComponent.js, HomeInfo.js

Also good practice is when file name and component name are the same, e.g. App.js => `const App = ({someProp}) => (<p>{someProp}</p>)`,
SomeComponent.js => `const SomeComponent= ({someProp}) => (<p>{someProp}</p>)`,
HomeInfo.js => `const HomeInfo= ({someProp}) => (<p>{someProp}</p>)`,

2022-08-30 11:06 UTC, vickierose commented on src/componentsBasic/home/home-sections/home-Info/home-info.scss
> +      width: 705px;
For such a big block I'd rcommend to place sizes in % so it had basic responsiveness by default

2022-08-30 11:06 UTC, vickierose commented on src/componentsBasic/home/home-sections/home-subscribe/home-subscribe.scss
> +      padding-left: 11%;
again: why are you using % for padding?

2022-08-30 11:06 UTC, vickierose commented on src/componentsUniversal/button/button.scss
> +    @include BTN (#ffffff, 600, #59abb0, none, 10px, flex, row, center, center);
this mixin is useless in overall, you need to pass too many arguments and you have only 2 possible button styles. You can just have classNames for them

2022-08-30 11:06 UTC, vickierose commented on src/componentsBasic/home/home.js
> +      <Header/>
header and footer will be present on other pages too so it's better to move them 1 level up

2022-08-30 11:06 UTC, vickierose commented on src/componentsUniversal/footer/footer.js
> +                <a href="/" className="menu__footer-link">
in react for inner routes that do not lead to another website we use react-router: https://reactrouter.com/en/v6.3.0/getting-started/overview and it's `Link` or `NavLink` component

2022-08-30 11:06 UTC, vickierose commented on src/componentsUniversal/footer/footer.scss
> +    background-color: #59abb0;
I'd suggest to move colors to css or sass variables so they were in one place and could be updated easily

2022-08-30 11:06 UTC, vickierose commented on src/componentsUniversal/header/header.js
> +                  <a href="/" className="menu__link menu__link-header menu__link-first">Courses</a>
same here: look at react-router and replace `a` tags with it's Link or NavLink.
hint: NavLink is better for this case

2022-08-30 11:06 UTC, vickierose commented on src/componentsUniversal/header/header.scss
> +      width: 86px;
it's better to have 1 common class for links, without numbering and give them common width and align it's content whithin the component

2022-08-30 11:06 UTC, vickierose commented on src/stylesUniversal/mixins/mixins.scss
> +@mixin BTN($color, $fw, $bcg, $border, $br, $flex, $f-direction, $j-content, $a-items) {
there's no use of this specific one mixin, but having this file is a good idea

2022-08-31 15:18 UTC, vickierose approved these changes

2022-09-06 10:43 UTC, Nerevand approved these changes

2022-09-06 11:24 UTC, merged